version: 2.1
orbs:
  node: circleci/node@2.0.3
  heroku: circleci/heroku@1.0.1
jobs:
  test:
    executor:
      name: node/default
    steps:
      - run: dir 
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
  test2:
    executor:
      name: node/default
    steps:
      - run: dir 
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
workflows:
  test&build&deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
      - test2:
          requires:
            - test
          filters:
            branches:
              ignore:
                - main