version: 2.1
orbs:
  node: circleci/node@2.0.3

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
  test1:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run coverage
workflows:
  test&build&deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - test1:
          requires:
            - test
          filters:
            branches:
              only:
                - master