version: 2.1
orbs:
  node: circleci/node@2.0.3
  heroku: circleci/heroku@1.0.1
jobs:
  test-lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
  test-coverage:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: mkdir .nyc_output && npm run cover:merge && npm run cover:report
  test-load:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: sudo npm install forever -g
      - run:
          command: forever start index.js
      - run:
          command: npm run test:load
      - run:
          command: forever stopall             
workflows:
  test&build&deploy:
    jobs:
      - test-lint:
          filters:
            branches:
              ignore:
                - main
      - test-coverage:
          filters:
            branches:
              ignore:
                - main
      - test-load:
          filters:
            branches:
              ignore:
                - main
